// <auto-generated />
using System;
using System.Collections.Generic;
using ApplyWise.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApplyWise.Api.Data.Migrations
{
    [DbContext(typeof(ApplyWiseDbContext))]
    [Migration("20260630125040_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApplyWise.Api.Data.Entities.JobMatchAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoverLetterDraft")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cover_letter_draft");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_description");

                    b.Property<string>("LinkedinMessageDraft")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("linkedin_message_draft");

                    b.Property<int>("MatchScore")
                        .HasColumnType("integer")
                        .HasColumnName("match_score");

                    b.PrimitiveCollection<List<string>>("MissingKeywords")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("missing_keywords");

                    b.PrimitiveCollection<List<string>>("RecommendedBullets")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("recommended_bullets");

                    b.Property<string>("ResumeText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resume_text");

                    b.PrimitiveCollection<List<string>>("StrongPoints")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("strong_points");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.PrimitiveCollection<List<string>>("WeakPoints")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("weak_points");

                    b.HasKey("Id");

                    b.ToTable("job_match_analyses", null, t =>
                        {
                            t.HasCheckConstraint("ck_job_match_analyses_match_score", "match_score BETWEEN 0 AND 100");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
